config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    member do
      get :add_bug
      get :show_bug
      post :assign_bug
      post :adds
      post :update_bug
      delete :remove_bug
      delete :remove
    end

    resources :bugs, except: [:index, :show]
  end

  root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :manager, class_name: :User, foreign_key: :manager_id

  has_many :bugs, dependent: :destroy
  has_many :project_users
  has_many :users, through: :project_users

  validates :name, presence:true, length: { minimum: 2, maximum: 40 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show,  :edit, :adds, :add_bug, :remove, :show_bug,:assign_bug, :remove_bug, :update_bug]
  before_action :set_user, only: [:create, :update, :destroy]
  before_action :set_user_projects, only: [:update, :destroy]
  before_action :set_user_params, only: [:remove, :adds]
  before_action :set_bug,  only: [:assign_bug, :remove_bug, :update_bug]
  before_action :set_developer, only: [:assign_bug, :remove_bug]

  before_action :authenticate_user!

  def index
    authorize Project
    @projects = policy_scope(Project)
  end

  def create
    authorize Project.new
    @project = @user.projects.create(project_params)
    if @project.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def new
    @project = Project.new
    authorize @project
  end

  def edit
    authorize @project
  end

  def show
    authorize @project
    working_users = @project.users
    @qa = working_users.select{ |user| user.type == "Qa" }
    @dev = working_users.select{ |user| user.type == "Developer" }
    @qa_developers = User.qa_dev
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    authorize @project
    if @project.destroy
      redirect_to root_path
    end
  end

  def remove
    authorize @project
    if ProjectUser.find_by(user: @user, project: @project).destroy
      redirect_to @project
    end
  end

  #adding developer and QA to the project
  def adds
    authorize @project
    @project_user = ProjectUser.create(user: @user, project: @project)
    redirect_to @project
  end

  def add_bug
    authorize @project
  end

  #showing all bugs belongs to the project and unassigned to any other developers
  def show_bug
    authorize @project
    @developer_bugs = @project.bugs.where(developer: current_user)
    @unassigned_bugs = @project.bugs.all
  end

  def assign_bug
    authorize @project
    @bug.developer_id = current_user.id
    if @bug.save
      redirect_to show_bug_project_path
    end
  end

  def remove_bug
    authorize @project
    if @bug.update_attributes(developer_id: nil)
      redirect_to show_bug_project_path
    end
  end

  def update_bug
    authorize @project
    if @bug.update_attributes(:status => "Resolved")
      redirect_to show_bug_project_path
    end
  end

  private
    def project_params
      params.require(:project).permit(:name)
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def set_user
      @user = User.find(current_user.id)
    end

    def set_user_projects
      @project = @user.projects.find(params[:id])
    end

    def set_user_params
      @user = User.find(params[:user_id])
    end

    def set_bug
      @bug = Bug.find(params[:bug_id])
    end

    def set_developer
      @user =  User.find(params[:developer_id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_footer.html.erb
<!-- Footer -->
<!-- Footer -->
<footer class="page-footer font-small black darken-3">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!--Pinterest-->
          <a class="pin-ic">
            <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <%= link_to "Bugzilla", root_path %>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/projects/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= link_to "BUGZILLA", root_path, class: "navbar-brand" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" >
      <li class="nav-item active">
        <%= link_to "Home", root_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <% if !user_session %>
          <%= link_to "SignUp", new_user_registration_path, :class => 'nav-link'%>
      <li class="nav-item dropdown">
          <%= link_to "SignIn", user_session_path, :class => 'nav-link'%>
        <% end %>
      </li>
    </ul>
    <ul class="pull-left">
      <% if user_session %>
       <strong class="text-uppercase"> <%= current_user.name%></strong>
       <div><%= current_user.type%></div>
      <% end %>
    </ul>
    <ul class="pull-left">
      <% if current_user.present? %>
        <% if user_session %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => 'nav-link') %>
        <% end %>
        <% end %>
    </ul>
  </div>
</nav>

app/views/projects/_project.html.erb
<div class="container">
  <div class="">
    <%= form_for @project do |f| %>
      <h2>Create New Project</h2>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :Project_Name%><br>
        <%= f.text_field :name, minlength: 2, maxlength:30, :required => true, :placeholder => "Project Name" %><br>
     </div>
     <%= f.submit :class => "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/projects/add_bug.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <h1>Projects</h1>
    <table class="table">
      <tr>
        <th>Project id</th>
        <th>Project name</th>
        <th>BUGS</th>
        <th></th>
      </tr>
      <tr>
        <td> <%= @project.id %> </td>
        <td> <%= @project.name %> </td>
        <td>
          <table>
            <tr>
              <th>Title</th>
              <th>Type</th>
              <th>Status</th>
              <th>Creater Name</th>
            </tr>
            <% @project.bugs.each do |bug| %>
              <tr>
              <td><%= bug.title %></td>
              <td><%= bug.bug_type %></td>
              <td><%= bug.status %></td>
              <td><%= bug.qa.name %></td>
              <% if policy(bug).destroy? %>
                <td><%= link_to "Remove", [@project ,bug], method: :delete, data:{ confirm:"Are You sure?" } %></td>
                <td><%= link_to "Edit", edit_project_bug_path(@project, bug) %></td>
              <% end %><br>
              </tr>
            <% end %>
          </table>
        </td>
      </tr>
    </table>
  </div>
  <div class="row justify-content-md-center" id="addbug">
    <%= form_with(model: [@project, @project.bugs.build], local: true) do |form| %>
     <h2>Add New Bug or Feature</h2>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title, minlength: 5, maxlength:30, :required => true, :class => "form-controler", :placeholder => "Title"  %>
      </p>
      <p>
        <%= form.label :deadline %><br>
        <%= form.text_field :deadline , minlength: 5, maxlength:30, :class => "form-controler", :placeholder => "Deadline" %>
      </p>
      <p>
        <%= form.label :type %><br>
        <%= form.select :bug_type, ['Bug','Feature'], :required => true, :id => "type" %>
      </p>
      <p>
        <%= form.label :status %><br>
        <%= form.select :status, [ 'New', 'Started', 'Completed'], :required => true, :id => "status" %> </p>
      <p>
      <p>
        <%= form.hidden_field :qa_id, :readonly => true, :id => "qa_id", value:current_user.id  %>
      </p>
      <p>
      <p> <%= form.label :screenshot %><br>
         <%= form.file_field :screenshot, :class => "btn btn-primary" %>
      </p>
       <%= form.submit :class => "btn btn-primary"%>
      </p>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <%= form_for @project do |f| %>
      <div><h2>Edit Project</h2></div>
      <div class="form-group">
        <label for="exampleInputEmail1">Project Name</label>
        <%= f.text_field :name, minlength: 2,  :required => true, :class => "form-control" %><br>
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div >
      <h1>All Project</h1>
    </div>
    <table class="table">
      <tr>
        <th>Project id</th>
        <th>Projects name</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @projects.each do |project| %>
        <tr>
          <td> <%= project.id%></td>
          <td> <%= project.name %></td>
          <% if policy(project).update? %>
            <td><%= link_to "Edit", edit_project_path(project) %></td>
            <td><%= link_to "Delete", project_path(project.id), method: :delete, data:{ confirm:"Are You sure?" } %></td>
            <td> <%= link_to "Add QA & Developer", project_path(project.id) %></td>
          <% end %>
          <%  if policy(project).add_bug? %>
            <td> <%= link_to "Report Bugs", add_bug_project_path(project.id) %></td>
          <% end %>
          <%  if policy(project).show_bug? %>
            <td> <%= link_to "Assign Bugs", show_bug_project_path(project.id) %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <%  if policy(@projects).create? %>
      <%= link_to "New Project", new_project_path  %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
  <%= render 'project'%>

app/views/projects/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <table class="table">
      <tr>
        <th>Project id</th>
        <th>Projects name</th>
        <th>Developer</th>
        <th>QA</th>
        <th>BUGS</th>
      </tr>
      <tr>
        <td><%= @project.id%></td>
        <td> <%= @project.name %></td>
        <td>
         <% if @dev.present? %>
           <% @dev.each do |developer| %>
              <%= developer.name %>
              <%= link_to "Remove ", remove_project_path(@project.id, user_id: developer.id), method: :delete, data:{confirm:"Are You sure?" } %> <br>
            <% end %>
          </td>
          <% end %>
          <% if @qa.present?%>
          <td>
            <% @qa.each do |sqa| %>
              <%= sqa.name %>
              <%= link_to "Remove ", remove_project_path(@project.id, user_id: sqa.id), method: :delete, data:{ confirm:"Are You sure?" } %> <br>
            <% end %>
          <% end %>
        </td>
        <td>
          <table>
            <tr>
              <th>Name</th><th>Type</th><th>Status</th>
            </tr>
            <% @project.bugs.each do |bug|%>
              <tr>
                <td><%= bug.title%></td><td><%= bug.bug_type%></td><td><%= bug.status%></td>
              </tr>
            <% end %>
          </table>
        </td>
      </tr>
    </table><br><br>
    <table class="table">
      <tr>
        <th>ID</th>  <th>Name</th>  <th>Developers and QA</th>  <th></th>
      </tr>
      <% if @qa_developers.present? %>
        <% @qa_developers.each do |qa_developer|%>
          <tr>
            <td> <%= qa_developer.id %></td>
            <td> <%= qa_developer.name %></td>
            <td> <%= qa_developer.type %></td>
            <td> <%= link_to "Assign to Project",  adds_project_path(@project, user_id: qa_developer.id), method: :post   %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/projects/show_bug.html.erb
<div class="container">
  <div class="row">
    <table class="table">
      <tr>
        <th>Project id</th>
        <th>Projects name</th>
        <th>BUGS</th>
        <th></th>
      </tr>
      <tr>
        <td>
           <%= @project.id%>
        </td>
        <td>
           <%= @project.name %>
        </td>
        <td>
          <table>
            <tr>
              <th>Name</th>
              <th>Type</th>
              <th>Status</th>
              <th></th>
              <th></th>
            </tr>
            <% @developer_bugs.each do |bug| %>
              <tr>
                <td><%= bug.title%></td>
                <td><%= bug.bug_type%></td>
                <td><%= bug.status%></td>
                <td><%= link_to "Mark Resolved",  update_bug_project_path(bug_id: bug.id), method: :post %></td>
                <td><%= link_to "Remove",  remove_bug_project_path(developer_id: current_user.id, bug_id: bug.id), method: :delete, data:{ confirm:"Are You sure?" } %>
                </td>
              </tr>  
            <% end %>
          </table>
        </td>
      </tr>
    </table>
   </div>
    <div class="row">
      <table class="table">
        <tr>
          <th>BUG ID</th>
          <th>BUG NAME</th>
          <th>BUG STATUS</th>
          <th></th>
        </tr>
        <% @unassigned_bugs.each do |bug| %>
          <tr>
            <td><%= bug.id %></td>
            <td><%= bug.title %></td>
            <td><%= bug.status %></td>
              <% if policy(@project).assign_bug? %>
                <td>
                <%= link_to "Assign Bug",  assign_bug_project_path(developer_id: current_user.id, bug_id: bug.id), method: :post %>
                </td>
              <% end %>
          </tr>
        <% end %>
      </table>
  </div>
</div>