config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    member do
      get :add_bug
      get :show_bug
      post :assign_bug
      post :adds
      post :update_bug
      delete :remove_bug
      delete :remove
    end

    resources :bugs, except: [:index, :show]
  end

  root "projects#index"
end

app/models/bug.rb
class Bug < ApplicationRecord
  mount_uploader :screenshot, ScreenshotUploader

  belongs_to :project
  belongs_to :developer, class_name: :User, foreign_key: :developer_id, optional:true
  belongs_to :qa, class_name: :User, foreign_key: :qa_id

  validates :title, presence: true, length: {minimum: 5, maximum: 40}
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_project, only: [:destroy, :create,  :update, :edit ]
  before_action :set_bug, only: [:edit, :destroy, :update]

  def create
    authorize Bug
    @bug = @project.bugs.build(bug_params)
    if @bug.save
      redirect_to add_bug_project_path(@project.id)
    end
  end

  def new; end

  def edit; end

  def update
    authorize @bug
    @bug = @project.bugs.find(params[:id])
    if @bug.update_attributes(bug_params)
      redirect_to add_bug_project_path(@project.id)
    end
  end

  def destroy
    if policy(@bug).destroy?
      @bug.destroy
      redirect_to add_bug_project_path(@project.id)
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_bug
       @bug = Bug.find(params[:id])
    end

    def bug_params
      params.require(:bug).permit(:title, :deadline, :status, :screenshot, :bug_type, :qa_id)
    end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="">
      <%= form_for([@bug.project, @bug]) do |form| %>
       <h2>Add New Bug or Feature</h2>
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title, minlength: 5, maxlength:30, :required => true, :class => "form-controler", :placeholder => "Title"  %>
        </p>
        <p>
          <%= form.label :deadline %><br>
          <%= form.text_field :deadline , minlength: 5, maxlength:30, :class => "form-controler", :placeholder => "Deadline" %>
        </p>
        <p>
          <%= form.label :type %><br>
          <%= form.select :bug_type, ['Bug','Feature'], :required => true, :id => "type" %>
        </p>
        <p>
          <%= form.label :status %><br>
          <%= form.select :status, [ 'New', 'Started', 'Completed'], required: true, id: 'status' %> </p>
        <p>
        <p>
          <%= form.hidden_field :qa_id, :readonly => true, :id => "qa_id", value: current_user.id  %>
        </p>
        <p>
        <p> <%= form.label :screenshot %><br>
           <%= form.file_field :screenshot, :class => "btn btn-primary" %>
        </p>
         <%= form.submit :class => "btn btn-primary"%>
        </p>
      <% end %>
    </div>
  </div>
  <%= link_to "Back",  projects_path %>
</div>